name: BIBS for Android
description: Ứng dụng BIBS cho thu ngân trên Android box
full_description: |
  Ứng dụng BIBS cho thu ngân trên Android box với các tính năng:
  <br>- Quản lý bàn cho khu vực
  <br>- Tính tiền và xác nhận thanh toán cho bàn
  <br>- Bật và tắt đèn khi khách đến và chuẩn bị thanh toán ra về
  <br>- In hóa đơn
  <br>- Xác nhận và cập nhật trạng thái gọi đồ, dịch vụ
android: https://github.com/supavn/supa-bibs-landing-page/releases/download/v1.0/app-release.apk
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
producthunt: https://telegra.ph/Replace-this-link-07-23
companies:
  - url: https://telegra.ph/Replace-this-link-07-23
    image: androidpolice.png
  - url: https://telegra.ph/Replace-this-link-07-23
    image: producthunt.png
